# Tensor
## Tensor의 특징
- NN에서 가장 중요한 연산은 행렬간의 곱이라 생각한다.
- matrix연산을 수행하는 모듈로 Numpy module이 있는데, numpy의 array가 ndarray인데 이를 gpu에서 사용가능하게 셋팅한게 Tensor라 이해하면 편하다.
- 실제로 tensor는 ndarray와 매우 유사하며, 메모리를 서로 공유할 수 있다.


In [1]:
import torch
import numpy as np

## Tensor의 초기화
- 텐서의 초기화 방법은 크게 3가지가 있다.
  - 데이터로부터 직접 생성, numpy array로부터 생성, 다른 텐서로부터 생성이다

In [7]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

x_ones = torch.ones_like(x_data) # *_like 메서드들은 속성(shape, dtype, device)을 카피한다
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float) # 이게 dtype도 카피를 하는거같은데, rand같은 경우는 int타입에서 에러떠서 float로 정의
print(x_rand)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 1],
        [1, 1]])
tensor([[0.7000, 0.2097],
        [0.7868, 0.0407]])


## Tensor의 ones, zeros, rand
- torch는 numpy처럼 ones, zeros, rand를 제공한다.
- 참고로 ones_, zeros_, rand_처럼 맨뒤에 _ 가 붙은 메소드는 덮어쓰기를 한다.

In [4]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
print(f"Random Tensor: \n {rand_tensor} \n")

ones_tensor = torch.ones(shape)
print(f"Ones Tensor: \n {ones_tensor} \n")

zeros_tensor = torch.zeros(shape)
print(f"Zeros Tensor: \n {zeros_tensor}")


Random Tensor: 
 tensor([[0.6796, 0.4683, 0.3852],
        [0.5754, 0.3788, 0.4945]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 텐서의 속성
- shape, dtype, device가 핵심 속성이다.

In [10]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 텐서 연산
- torch 모듈에 다양한 연산들이 있는데 이건 따로 공부를 해보도록 하자
- 텐서는 기본적으로 CPU에 생성되는데 .to('cuda') 메서드를 실행하면 gpu에서 연산하게끔 할 수 있다.
  - 물론 gpu가 사용가능한지 확인부터 해야한다.
  - 참고로 cpu에서 gpu로 옮기는 비용이 작지 않은것을 기억해두자
- numpy처럼 slicing이 자유로운점은 매우 편하다

In [11]:
torch.cuda.is_available()

True

In [12]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [19]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [20]:
t1 = torch.cat([tensor, tensor, tensor], dim=1) # 여기서 dim이 가변하는 dim을 하나 지정하는 것이다.
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [21]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

print(y1, y2, y3)

# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
# 내적아니다. 요소별 곱이다. 체크해둔다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1, z2, z3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [22]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)
tensor.add_(torch.tensor([1,2,3,4]))
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
tensor([[ 7.,  7.,  9., 10.],
        [ 7.,  7.,  9., 10.],
        [ 7.,  7.,  9., 10.],
        [ 7.,  7.,  9., 10.]])


In [23]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")
l = n.tolist()
print(f"l: {l}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
l: [1.0, 1.0, 1.0, 1.0, 1.0]
